### PR TITLE
⚙️ some cli testing on ci

### PR DESCRIPTION
**Pull request by stevejpurves**
possible new workflow to test cli installs over different OSs

### CODE REVIEW

**Comment by stevejpurves** [comment]
@rowanc1 blocks build fails on windows

**Comment by rowanc1** [comment]
Hm, this is good, but shouldn't run on every commit because it is testing prod npm.

**Comment by stevejpurves** [comment]
@rowanc1 ok we could remove the push to main trigger but on the pull_request all we can do there is not run it in draft mode? 


hm... wait...

**Comment by stevejpurves** [comment]
ok, I have changed this to `workflow_dispatch` for now, which just basically means that we can only use it as a post-publish check on something already deployed.

To go beyond that do we need 2 workflows? a first build workflow in an OS we support builds for, which makes a build artifact available, then this workflow that then downloads that build artifact only and does `npm -g install /local-folder` on the OS matrix in order to test the cli install process?

Then we trigger that either manually, pre-publish or on commits to main

**Pull request closed without merging**
